development: &development
  adapter: postgresql
  database: rigli_development

production:
  <<: *development

test: &test
  adapter: postgresql
  database: rigli_test
  min_messages: warning


cucumber:
  <<: *test
